### PR TITLE
Add option to debounce user input

### LINKED ISSUE #105: Pagefind UI: debounce user input?
### Discussed in https://github.com/CloudCannon/pagefind/discussions/104

<div type='discussions-op-text'>

<sup>Originally posted by **dprothero** October 21, 2022</sup>
Is there a way to have the UI debounce the user input? It's really distracting to have search results showing up for every key press.

In other words, don't have the search actually execute until something like 300ms after the last key press.</div>

### PR DESCRIPTION
**Pull request by dprothero**
Fixes #105 

Defaults to 300ms timeout after user input. Can set to 0 to disable.

### CODE REVIEW

**Comment by bglw** [comment]
Hi @dprothero 👋 

Thanks for jumping in 😍! The change looks good — the only tweak I'd like is that in its current state I'm keen to keep the default at 0. The primary reason is that sending the keystrokes through instantly is what allows Pagefind to preload the index it needs, which usually allows all the data to be loaded by the time a user finishes typing a search query. Debouncing the call to search means that loading only begins when you _stop_ typing, which on a slow network will compound the overall search response time.

I _would_ be okay with a default debounce value, but we'd need to make one of two changes:

1. Call the search function immediately but debounce showing the results
2. Better option: Debounce the search function as you have, but call [pagefind.preload](https://pagefind.app/docs/api/#preloading-search-terms) **not** debounced, as the user is typing.

Let me know if you have the bandwidth to make any of the changes above 🙂

**Comment by dprothero** [comment]
@bglw working on it now

**Comment by dprothero** [comment]
@bglw OK, take a look! I went with the `pagefind.preload` option.

**Comment by dprothero** [comment]
`translate` is returning an empty string and I can't figure out what is causing that. It doesn't seem to be my PR.

**Comment by dprothero** [comment]
I pushed a fix for the translation string loading. I'm not sure why it wasn't working.

**Review by bglw — APPROVED** [review]
Everything looks good 🤩 Thanks!

I have pushed one commit to fix a race condition:

If I typed a query (say, `golly`), and then backspaced it quickly letter by letter, when the term became falsy the ui would set `searched` to false, but then after the delay the debounced call for `g` would trigger and put us back into a searching state. 

Fixed by also clearing the debounce timer if the search input empties.

If you're happy with that change I'll merge this and get it released very soon 🙂

**Comment by bglw** [comment]
> I pushed a fix for the translation string loading. I'm not sure why it wasn't working.

Sorry — looks like one of my other changes wasn't correct 🥸 oops! Thanks for the fix 😅

**Comment by bglw** [comment]
Actually going to merge this now so that I have to deal with the merge conflicts with #116 myself 🙂

**Pull request merged**
