### PR TITLE
Add Persian translation

### PR DESCRIPTION
**Pull request by YektaDev**
This PR adds Persian translation.

### CODE REVIEW

**Comment by bglw** [comment]
Hi @YektaDev ! 👋 

Sorry for the delay — I have a couple of RTL language PRs open waiting, as I haven't done any work to ensure that Pagefind's UI works when displayed RTL. Would you have any insight into whether changes would be needed on Pagefind's side to support RTL language?

**Comment by YektaDev** [comment]
Hi @bglw!

Thanks for following up! I've seen a few tweaked previews where the Persian translation was manually provided, and overall, it worked quite well (with the test assuming the element is inside a page or a wrapper that has `dir="auto"`). One key adjustment that would be really necessary for full RTL support is swapping the positions of the search icon and the clear button. This one wouldn't be taken care of in case of adding the `dir="auto"` attribute.

I haven't observed any issues other than this. Feel free to reach out if you'd like more input!

**Comment by YektaDev** [comment]
Another point to mention is, the number assigned to `[COUNT]` should be localized, if it isn't already. For the implementation, `number.toLocaleString(locale)` gets the job done.

For example, in Persian:

+ Non-localized: "**1** نتیجه برای تست یافت شد"
+ Localized: "**۱** نتیجه برای تست یافت شد"

**Comment by bglw** [comment]
Excellent, and Pagefind does already use `Intl.NumberFormat` for this :) 

Will merge and collect feedback for any improvements!

**Review by bglw — APPROVED** [review]

**Pull request merged**
