### PR TITLE
Swedish translation

### PR DESCRIPTION
**Pull request by mntzrr**

### CODE REVIEW

**Review by bglw — APPROVED** [review]

**Comment by bglw** [comment]
Thanks @mntzrr! ❤️

**Comment by bglw** [comment]
Hi @mntzrr — this is now out with [v0.11.0](https://github.com/CloudCannon/pagefind/releases/tag/v0.11.0) :)

**Comment by mntzrr** [comment]
Awesome! I’ll be looking into adding Arabic translation next.

**Comment by bglw** [comment]
Oh grand — do let me know if anything needs to change in the UI styling to handle the RTL layout

**Pull request merged**
