### PR TITLE
Skip user's profile when invoking powershell

### PR DESCRIPTION
**Pull request by tylermercer**
Pagefind fails for me unless I comment out my powershell profile. Adding this flag should fix this.

(I was unable to get pagefind running even after cloning my fork. The instructions in CONTRIBUTING.md did not work for me.)

### CODE REVIEW

**Comment by bglw** [comment]
Thanks!

Yes, I need to update the CONTRIBUTING.md — which might also need some attention for running from source on Windows.

This change looks sane, so happy to merge 🙂

**Comment by tylermercer** [comment]
Thanks for getting to this so quickly!! I'll definitely keep an eye out for when this is released!

**Comment by bglw** [comment]
Hopefully soon! Waiting on rust-lang/crates.io#6028 so I can compile/publish again, but I was hoping to get something out this week. I'll drop a comment here when it goes out 🙂

**Comment by tylermercer** [comment]
Thank you!!

**Comment by bglw** [comment]
Hi @tylermercer — sorry for the delay, a few more things got rolled into the release. This is now out with [v0.11.0](https://github.com/CloudCannon/pagefind/releases/tag/v0.11.0) 😄

**Comment by tylermercer** [comment]
Just reenabled my profile on my local machine and Pagefind now works great!! This is awesome. 🎉 

I noticed that it uses Powershell's IWR. I remember one of my coworkers finding that suppressing the visual loader for IWR makes it faster. If I can remember how he did it (it's some obscure parameter or something), I'll have another PR for you at some point. 😄

Thanks for letting me know it was released!

**Comment by tylermercer** [comment]
The trick is to add `$global:ProgressPreference = "SilentlyContinue";` before the Invoke-WebRequest call... but it doesn't seem to be working when calling powershell using child_process. 

Given that it caches the download, though, I don't think the lag added by the visual loader is worth worrying about beyond that. But if you decide to try it, let me know!

Sorry for keeping this comment thread going. Figured it wasn't worth making an issue just to say my attempt to speed it up didn't work. 😅

**Comment by bglw** [comment]
No worries! I'm not often on a Windows machine so it's unlikely I'll look at this, but feel free to ping me again if there is something worth fixing in there 🙂

**Pull request merged**
