### PR TITLE
Fix issue where anchors and weights will escape through meta and filters

### PR DESCRIPTION
**Pull request by bglw**
For #681

### CODE REVIEW

**Comment by dscho** [comment]
@bglw do you plan on publishing this version to npmjs.com?

**Comment by bglw** [comment]
👋 @dscho yep! hopefully within a week, just need to solve our ci/testing woes to get it out

**Comment by dscho** [comment]
Thank you! Good luck with CI!

**Comment by bglw** [comment]
@dscho released

**Comment by dscho** [comment]
> @dscho released 

Thank you!

**Pull request merged**
