### PR TITLE
Add a configurable autofocus option

### PR DESCRIPTION
**Pull request by vanbroup**
The default of this option is off.

Related #121

### CODE REVIEW

**Review by bglw — APPROVED** [review]

**Comment by bglw** [comment]
Lovely! Thank you 🙏

**Comment by bglw** [comment]
Available in `1.0.5-rc0` for now 🙂

**Comment by nhoizey** [comment]
@bglw should this be mentioned [in the docs here](https://pagefind.app/docs/ui/#autofocus), so people don't struggle to understand why it doesn't work with current stable 1.0.4 release? 😅

**Comment by bglw** [comment]
Whoops! I don't think I intended for those pages to have gone to the production docs branch yet, my bad!

Thank I'm prepping a stable release _very_ soon, so it won't be lying for long 😅

**Comment by nhoizey** [comment]
Ok, this is good news!

**Comment by bglw** [comment]
Released on v1.1.0 :)

**Pull request merged**
