### PR TITLE
Add Arabic UI Translations

### PR DESCRIPTION
**Pull request by LuchoTurtle**
This is a micro-PR that should be quickly mergeable (in the same vein as https://github.com/CloudCannon/pagefind/pull/690).

It's an RTL language.

I'm not Saudi nor from the UAE nor from the region, but I'll find this added useful in the future, so I "hired" a certified translator to do this for me (credited in the `json` file) who generously did it for free. So I'm sure it is accurate :)

### CODE REVIEW

**Review by nelsonic — APPROVED** [review]
LGTM 🇦🇪👌

**Comment by bglw** [comment]
Hey! Sorry for the delay. There was a pre-existing PR for the same file which has gone out in the latest release. Let me know if there's consensus on those translations, or if any changes should be made!

**Comment by LuchoTurtle** [comment]
I'm not a native speaker. I just know a certificated translator did these changes. I'll leave it up to you or wait for other opinions on which one is the best version 😉

**Comment by bglw** [comment]
Closing this out for now, but feel free to reopen or open another if there are improvements to be made to the existing translations 🙂

**Pull request closed without merging**
