### PR TITLE
Added Romanian translation

### PR DESCRIPTION
**Pull request by mateesville93**

### CODE REVIEW

**Comment by mateesville93** [comment]
Will be nice to have something like this: `zero_results` / `one_results` / `few_results` / `other_results` 
Here is a reference for ranges:
https://www.unicode.org/cldr/charts/44/supplemental/language_plural_rules.html#ro

**Comment by mateesville93** [comment]
Someone to merge this PR?

**Review by bglw — APPROVED** [review]

**Comment by bglw** [comment]
Hey @mateesville93 , sorry for the delay! Merging now, and I'll ping you again when the next release lands.

**Comment by bglw** [comment]
Released in [released in v1.1.0](https://github.com/CloudCannon/pagefind/releases/tag/v1.1.0), thanks again!

**Pull request merged**
